from ubuntu:16.04
RUN apt-get update && apt-get upgrade 
RUN apt-get -y install gcc git gcc-multilib 
RUN apt-get -y install make
ADD ./FreeRTOS-Sim /FreeRTOS-Sim
WORKDIR /FreeRTOS-Sim
CMD make clean && make all && ./FreeRTOS-Sim
