/*  THIS FILE WAS GENERATED BY THE DATALIGHT RELIANCE EDGE CONFIGURATION
    UTILITY.  DO NOT MODIFY.

    Generated by configuration utility version 2.3
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 512U, 4000000U, 0U, false, 100U, 3U, "VOL0:" } //2 GB SD Card, only formatting ~1 GB

    //Sector size, number of sectors, sector offset, atomic sector write, inode (file and directory) count, number of block retries, path prefix for volume
};
